### PR TITLE
Add unit tests for prepare_categorical_data

### PR DESCRIPTION
**Pull request by premsrii**
This PR adds unit tests for the function `prepare_categoriccal_data()`. The function is also modified to handle only non-numerical data.

### CODE REVIEW

**Review by chrislemke — CHANGES_REQUESTED** [review]

**Comment by chrislemke** [comment]
Looks good so far. Could you check if all unit tests pass on your machine? There seems to be an issue with the test on the CI and I just want to make sure everything runs. And please pull all changes from `main` before running the tests. Thanks!

**Comment by premsrii** [comment]
`=========================== short test summary info ============================
FAILED tests/test_feature_selection/test_reviser.py::test_revise_classifier_for_fit_attribute
FAILED tests/test_feature_selection/test_reviser.py::test_revise_classifier_columns
FAILED tests/test_feature_selection/test_reviser.py::test_revise_classifier_feature_importance
FAILED tests/test_feature_selection/test_reviser.py::test_revise_classifier_correlation
FAILED tests/test_feature_selection/test_reviser.py::test_revise_classifier_chi2
FAILED tests/test_feature_selection/test_reviser.py::test_revise_classifier_f_statistic
FAILED tests/test_feature_selection/test_selector.py::test_select_with_classifier_column_shape_with_k_best
========================= 7 failed, 23 passed in 0.20s =========================`

The failed tests do not belong to the files modified by me.

**Comment by premsrii** [comment]
> Looks good so far. Could you check if all unit tests pass on your machine? There seems to be an issue with the test on the CI and I just want to make sure everything runs. And please pull all changes from `main` before running the tests. Thanks!

All tests are passing now. I have modified other files because of changes in `prepare_categorical_data()`.

**Comment by chrislemke** [comment]
@premsrii If you need help resolving the merge conflict. We could do it together.

**Review by chrislemke — APPROVED** [review]

**Pull request merged**
